server:
  http:
    enabled: true
    port: 8080
  https:
    enabled: true
    port: 8443
    caCert: certs/test-root-cert.pem
    caKey:  certs/test-root-key.pem
    serverCert: certs/test-server-cert.pem
    serverKey: certs/test-server-key.pem
  rootInitPubKey: certs/test-root-init-public.pem
  rootInitPriKey: certs/test-root-init-private.pem
dataStore:
  type: InMemoryDataStore
keyStore:
  type: InMemoryKeyStore
